# 1) Edit with default SSH key loaded from .config on main desktop:
#      sops secrets/common.yaml
#
# 2) Tell sops to use the generated key and edit
#      export SOPS_AGE_KEY_FILE=/var/lib/sops-nix/key.txt
#
# 2b) Now you can edit/decrypt, e.g.:
#      sops secrets/common.yaml
#      sops secrets/cloudflare.env

keys:
  # Admin/editor key (workstation; used to edit secrets)
  - &admin age122lwhcyezhf8a93409c3tual02cuex63pj6tz2auwl2vumvjpcxshatuaq

  # Relic host system-managed key (from /var/lib/sops-nix/key.pub)
  - &host_relic age1syul9dkj56dj0flwmcu8nl8dnk60ctdx4el7ynv5h8p7e0uxu3kqa2rmcc

  # Gemini host system-managed key (from /var/lib/sops-nix/key.pub)
  - &host_gemini age1728fenm3v5dpuhln56g3jzn7035ajgedlfxn7gvvey5u98s4h3ksup52kk

creation_rules:
  # Shared secrets file for all hosts (add hosts here as they come online)
  - path_regex: ^secrets/common\.yaml$
    key_groups:
      - age:
        - *admin
        - *host_relic
        - *host_gemini
        # - *host_midship

  # Cloudflare environment variables (.env format) shared/consumed by services
  - path_regex: ^secrets/cloudflare\.env$
    key_groups:
      - age:
        - *admin
        - *host_gemini

  # Overseer discord bot for EVE online. containts bot token.
  - path_regex: ^secrets/overseer\.env$
    key_groups:
      - age:
        - *admin
        - *host_gemini

  # Optional per-host files in a hosts/ subfolder (add a rule per host as needed)
  - path_regex: ^secrets/hosts/relic\.yaml$
    key_groups:
      - age:
        - *admin
        - *host_relic
