# ============================================================================
# SOPS / AGE WORKFLOW
# ============================================================================
#
# EDITING SECRETS
#   sops secrets/filename.yaml
#
# ADDING A NEW HOST
#   1. Bootstrap host:
#        ./bootstrap.sh <hostname>
#      (The OS install includes `profiles/base.nix`, which configures sops-nix
#       to auto-generate a key at /var/lib/sops-nix/key.txt on first boot)
#
#   2. Get public key from new host:
#        ssh user@host "cat /var/lib/sops-nix/key.txt"
#      (The public key is typically in the file header comment)
#
#   3. Register key in this file:
#      - Add public key to 'keys:' list below with a new anchor (&host_name)
#      - Add *host_name to relevant 'creation_rules' key groups
#
#   4. Re-encrypt secrets for the new key:
#        sops updatekeys secrets/mail2discord.yaml
#        sops updatekeys secrets/cloudflare.env
#        # etc...
#
#   5. Deploy:
#        nh os switch
# ============================================================================

keys:
  # Admin/editor key (workstation; used to edit secrets)
  - &admin age122lwhcyezhf8a93409c3tual02cuex63pj6tz2auwl2vumvjpcxshatuaq

  # Relic host system-managed key (from /var/lib/sops-nix/key.pub)
  - &host_relic age1syul9dkj56dj0flwmcu8nl8dnk60ctdx4el7ynv5h8p7e0uxu3kqa2rmcc

  # Gemini host system-managed key (from /var/lib/sops-nix/key.pub)
  - &host_gemini age1728fenm3v5dpuhln56g3jzn7035ajgedlfxn7gvvey5u98s4h3ksup52kk

  # Midship host system-managed key (will be added after first deployment)
  - &host_midship age16epgh7d6a7wndqyntsd0v9t7vdqqzgmy9eh45zrgwe76rnj8aa8s8yqcmq

  # Lockout host system-managed key (will be added after first deployment)
  - &host_lockout age1jpkrww5fkru0e8jau2cdq9f0l9m8y00ct0d82zzjd48h9swzu9ks0x5gv0

  # Coagulation host system-managed key (will be added after first deployment)
  - &host_coagulation age1mg7eku8ufec2mnsf8w6uc45vden64nqs3ns4ee75tyrqu0eu0duslcdv28

creation_rules:
  # Mail2Discord webhook secret (used by mail2discord service on all hosts)
  - path_regex: ^secrets/mail2discord\.yaml$
    key_groups:
      - age:
        - *admin
        - *host_relic
        - *host_gemini
        - *host_lockout
        - *host_midship
        - *host_coagulation

  # Cloudflare environment variables (.env format) shared/consumed by services
  - path_regex: ^secrets/cloudflare\.env$
    key_groups:
      - age:
        - *admin
        - *host_gemini
        - *host_midship

  # Overseer discord bot for EVE online. containts bot token.
  - path_regex: ^secrets/overseer\.env$
    key_groups:
      - age:
        - *admin
        - *host_gemini
        - *host_midship

  # Prism environment variables (.env format) for server management
  - path_regex: ^secrets/prism\.env$
    key_groups:
      - age:
        - *admin
        - *host_midship

  # Minecraft RCON password (.env format) for server management
  - path_regex: ^secrets/minecraft-rcon\.env$
    key_groups:
      - age:
        - *admin
        - *host_gemini
        - *host_midship
        - *host_coagulation

  # Reddit Watch Exchange Monitor webhook (dotenv format)
  - path_regex: ^secrets/reddit-webhook\.env$
    key_groups:
      - age:
        - *admin
        - *host_relic
