# 1) Edit secrets with your admin SSH key (loaded from .config on main desktop):
#      sops secrets/mail2discord.yaml
#
# 2) Or tell sops to use a host's generated key:
#      export SOPS_AGE_KEY_FILE=/var/lib/sops-nix/key.txt
#
# 2b) Now you can edit/decrypt, e.g.:
#      sops secrets/mail2discord.yaml
#      sops secrets/cloudflare.env

keys:
  # Admin/editor key (workstation; used to edit secrets)
  - &admin age122lwhcyezhf8a93409c3tual02cuex63pj6tz2auwl2vumvjpcxshatuaq

  # Relic host system-managed key (from /var/lib/sops-nix/key.pub)
  - &host_relic age1syul9dkj56dj0flwmcu8nl8dnk60ctdx4el7ynv5h8p7e0uxu3kqa2rmcc

  # Gemini host system-managed key (from /var/lib/sops-nix/key.pub)
  - &host_gemini age1728fenm3v5dpuhln56g3jzn7035ajgedlfxn7gvvey5u98s4h3ksup52kk

  # Coagulation host system-managed key (will be added after first deployment)
  - &host_coagulation <pending>

  # Midship host system-managed key (will be added after first deployment)
  - &host_midship <pending>

  # Beavercreek host system-managed key (will be added after first deployment)
  - &host_beavercreek <pending>

creation_rules:
  # Mail2Discord webhook secret (used by mail2discord service on all hosts)
  - path_regex: ^secrets/mail2discord\.yaml$
    key_groups:
      - age:
        - *admin
        - *host_relic
        - *host_gemini
        # Uncomment after retrieving keys from first deployment:
        # - *host_coagulation
        # - *host_midship
        # - *host_beavercreek

  # Cloudflare environment variables (.env format) shared/consumed by services
  - path_regex: ^secrets/cloudflare\.env$
    key_groups:
      - age:
        - *admin
        - *host_gemini

  # Overseer discord bot for EVE online. containts bot token.
  - path_regex: ^secrets/overseer\.env$
    key_groups:
      - age:
        - *admin
        - *host_gemini
